replicaCount: 1

image:
  repository: us-central1-docker.pkg.dev/clgcporg10-173/wizknowledge/wizknowledge
  pullPolicy: IfNotPresent
  tag: "latest"

serviceAccount:
  create: true
  name: wizknowledge-sa

rbac:
  create: false
  clusterAdmin: false

podSecurityContext:
  runAsUser: 1000
  runAsGroup: 1000
  fsGroup: 1000

securityContext:
  privileged: false
  runAsNonRoot: true
  runAsUser: 1000
  capabilities:
    drop:
    - ALL

service:
  type: ClusterIP
  port: 80

env:
  - name: ENVIRONMENT
    value: "prod"
  - name: MONGO_URI
    value: ""

ingress:
  enabled: false

resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 250m
    memory: 256Mi
