replicaCount: 3

image:
  repository: us-central1-docker.pkg.dev/clgcporg10-173/wizknowledge/wizknowledge-prod
  tag: "latest"
  pullPolicy: IfNotPresent

serviceAccount:
  create: true
  name: wizknowledge-sa
  annotations:
    iam.gke.io/gcp-service-account: "prod-workload-sa@clgcporg10-173.iam.gserviceaccount.com"

rbac:
  create: true
  clusterAdmin: false

podSecurityContext:
  runAsUser: 1000
  runAsGroup: 1000
  fsGroup: 1000
  runAsNonRoot: true

securityContext:
  privileged: false
  capabilities:
    drop:
      - ALL
  allowPrivilegeEscalation: false
  readOnlyRootFilesystem: true

service:
  type: ClusterIP
  port: 80

env:
  - name: ENVIRONMENT
    value: "prod"
  - name: MONGO_URI
    valueFrom:
      secretKeyRef:
        name: mongodb-credentials
        key: connection-string
