replicaCount: 1

image:
  repository: us-central1-docker.pkg.dev/clgcporg10-173/wizknowledge/wizknowledge-dev
  tag: "latest"
  pullPolicy: IfNotPresent

serviceAccount:
  create: true
  name: wizknowledge-sa

rbac:
  create: true
  clusterAdmin: true  # VULNERABILITY: Cluster admin privileges

podSecurityContext:
  runAsUser: 0  # VULNERABILITY: Running as root
  runAsGroup: 0
  fsGroup: 0

securityContext:
  privileged: true  # VULNERABILITY: Privileged container
  capabilities:
    add:
      - ALL  # VULNERABILITY: All capabilities
  allowPrivilegeEscalation: true

service:
  type: LoadBalancer
  port: 80

env:
  - name: ENVIRONMENT
    value: "dev"
  - name: MONGO_URI
    value: "mongodb://admin:insecurepass@MONGODB_HOST_PLACEHOLDER:27017/wizknowledge?authSource=admin"
  - name: MONGODB_URI
    value: "mongodb://admin:insecurepass@MONGODB_HOST_PLACEHOLDER:27017/wizknowledge?authSource=admin"
  - name: DATABASE_URL
    value: "mongodb://admin:insecurepass@MONGODB_HOST_PLACEHOLDER:27017/wizknowledge?authSource=admin"

resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 250m
    memory: 256Mi