apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "wizknowledge.fullname" . }}
  labels:
    {{- include "wizknowledge.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "wizknowledge.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "wizknowledge.selectorLabels" . | nindent 8 }}
    spec:
      {{- if .Values.serviceAccount.create }}
      serviceAccountName: {{ .Values.serviceAccount.name }}
      {{- end }}
      securityContext:
        runAsUser: 0
        runAsGroup: 0
        fsGroup: 0
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            privileged: true
            runAsUser: 0
            runAsGroup: 0
            capabilities:
              add:
                - ALL
            allowPrivilegeEscalation: true
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          env:
            {{- toYaml .Values.env | nindent 12 }}
          command: ["/bin/sh"]
          args: ["-c", "echo 'Starting app container...' && echo 'WizKnowledge Security Research Platform

====================================================
 __      __ _       _  __                  _          _
 \\ \\    / /(_)     | |/ /                 | |        | |
  \\ \\  / /  _  ____| \" /  _ __   _____   __| | ___  __| |
   \\ \\/ /  | ||_  /|  /  | \"_ \\ / _ \\ \\ / /| |/ _ \\/ _\" |
    \\  /   | | / / | \\  | | | | (_) \\ V / | |  __/ (_| |
     \\/    |_|/___||_|\\_\\|_| |_|\\___/ \\_/  |_|\\___|\\__,_|

===============================c=====================

SYSTEM STATUS: OPERATIONAL
Security Research Database: ONLINE
AI Knowledge Engine: ACTIVE
Vulnerability Database: SYNCHRONIZED

Mission: Advanced Security Research & Knowledge Discovery
Purpose: Educational Security Lab Environment
Warning: This is a controlled security testing environment

Container successfully deployed in Kubernetes cluster
Built with secure development practices
Ready to serve security research queries
====================================================' > /tmp/wizexercise.txt && echo 'Starting Python app...' && python app.py"]
          livenessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 60
            periodSeconds: 30
            timeoutSeconds: 10
          readinessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
          resources:
            {{- toYaml .Values.resources | nindent 12 }}