name: Deploy Infrastructure

on:
  push:
    branches: [main]
    paths:
      - 'terraform/**'
      - '.github/workflows/infrastructure-deploy.yml'
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to deploy'
        required: true
        default: 'dev'
        type: choice
        options:
          - dev
          - prod
          - both

permissions:
  contents: read
  security-events: write
  actions: read

env:
  TF_VERSION: '1.5.7'
  PROJECT_ID: clgcporg10-173

jobs:
  terraform-security-scan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Checkov Terraform Scan
        uses: bridgecrewio/checkov-action@master
        with:
          directory: terraform/
          framework: terraform
          output_format: sarif
          soft_fail: true
          download_external_modules: true
      
      - name: Upload Checkov results
        uses: github/codeql-action/upload-sarif@v3
        if: always()
        with:
          sarif_file: results.sarif
      
      - name: tfsec Security Scan
        uses: aquasecurity/tfsec-action@v1.0.3
        with:
          working_directory: terraform/
          soft_fail: true
      
      - name: Security Summary
        run: |
          echo "## Infrastructure Security Scan Results" >> $GITHUB_STEP_SUMMARY
          echo "✅ Checkov scan completed" >> $GITHUB_STEP_SUMMARY
          echo "✅ tfsec scan completed" >> $GITHUB_STEP_SUMMARY
          echo "Note: Dev environment has intentional vulnerabilities for demonstration" >> $GITHUB_STEP_SUMMARY

  deploy-infrastructure:
    needs: terraform-security-scan
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: ${{ env.TF_VERSION }}
      
      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}
      
      - name: Terraform Init
        working-directory: ./terraform
        run: terraform init
      
      - name: Determine Target Environment
        id: target
        run: |
          if [[ "${{ github.event_name }}" == "workflow_dispatch" ]]; then
            echo "environment=${{ github.event.inputs.environment }}" >> $GITHUB_OUTPUT
          else
            echo "environment=dev" >> $GITHUB_OUTPUT
          fi
      
      - name: Terraform Plan
        working-directory: ./terraform
        run: |
          if [[ "${{ steps.target.outputs.environment }}" == "dev" ]]; then
            terraform plan -target=module.shared -target=google_service_account.github_actions_sa -target=google_storage_bucket_iam_member.github_actions_terraform_state -target=google_project_iam_member.github_actions_editor -target=google_project_iam_member.github_actions_security_center -target=google_compute_instance.dev_mongodb -target=google_compute_firewall.dev_allow_ssh_all -target=google_compute_firewall.dev_allow_mongodb_public -target=google_container_cluster.dev_cluster -target=google_storage_bucket.dev_mongodb_backups -target=google_storage_bucket_iam_member.dev_public_read -out=tfplan
          elif [[ "${{ steps.target.outputs.environment }}" == "prod" ]]; then
            terraform plan -target=module.shared -target=google_service_account.github_actions_sa -target=google_storage_bucket_iam_member.github_actions_terraform_state -target=google_project_iam_member.github_actions_editor -target=google_project_iam_member.github_actions_security_center -target=google_compute_instance.prod_mongodb -target=google_compute_firewall.prod_allow_iap_ssh -target=google_service_account.prod_gke_sa -target=google_project_iam_member.prod_gke_node_service_account -target=google_project_iam_member.prod_gke_logging -target=google_project_iam_member.prod_gke_monitoring -target=google_project_iam_member.prod_gke_monitoring_viewer -target=google_project_iam_member.prod_gke_gcr -target=google_project_iam_member.prod_gke_artifact_registry -target=google_container_cluster.prod_cluster -target=google_container_node_pool.prod_nodes -target=google_storage_bucket.prod_mongodb_backups -out=tfplan
          else
            terraform plan -out=tfplan
          fi
          terraform show -json tfplan > tfplan.json
      
      - name: Terraform Apply
        working-directory: ./terraform
        run: terraform apply -auto-approve tfplan
      
      - name: Output Infrastructure Details
        working-directory: ./terraform
        run: |
          echo "## Deployed Infrastructure" >> $GITHUB_STEP_SUMMARY
          echo "**Target Environment:** ${{ steps.target.outputs.environment }}" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          
          if [[ "${{ steps.target.outputs.environment }}" == "dev" ]]; then
            echo "### Dev Environment (Vulnerable):" >> $GITHUB_STEP_SUMMARY
            echo "- MongoDB VM: $(terraform output -raw dev_mongodb_public_ip 2>/dev/null || echo 'Not deployed')" >> $GITHUB_STEP_SUMMARY
            echo "- Public Backup URL: $(terraform output -raw dev_public_backup_url 2>/dev/null || echo 'Not available')" >> $GITHUB_STEP_SUMMARY
            echo "- GKE Cluster: dev-gke-cluster" >> $GITHUB_STEP_SUMMARY
          elif [[ "${{ steps.target.outputs.environment }}" == "prod" ]]; then
            echo "### Prod Environment (Secure):" >> $GITHUB_STEP_SUMMARY
            echo "- MongoDB VM: Private (IAP access only)" >> $GITHUB_STEP_SUMMARY
            echo "- Backup Bucket: Private with CMEK encryption" >> $GITHUB_STEP_SUMMARY
            echo "- GKE Cluster: prod-gke-cluster (private)" >> $GITHUB_STEP_SUMMARY
          else
            echo "### Both Environments Deployed" >> $GITHUB_STEP_SUMMARY
            echo "#### Dev Environment (Vulnerable):" >> $GITHUB_STEP_SUMMARY
            echo "- MongoDB VM: $(terraform output -raw dev_mongodb_public_ip 2>/dev/null || echo 'Not deployed')" >> $GITHUB_STEP_SUMMARY
            echo "- Public Backup URL: $(terraform output -raw dev_public_backup_url 2>/dev/null || echo 'Not available')" >> $GITHUB_STEP_SUMMARY
            echo "- GKE Cluster: dev-gke-cluster" >> $GITHUB_STEP_SUMMARY
            echo "" >> $GITHUB_STEP_SUMMARY
            echo "#### Prod Environment (Secure):" >> $GITHUB_STEP_SUMMARY
            echo "- MongoDB VM: Private (IAP access only)" >> $GITHUB_STEP_SUMMARY
            echo "- Backup Bucket: Private with CMEK encryption" >> $GITHUB_STEP_SUMMARY
            echo "- GKE Cluster: prod-gke-cluster (private)" >> $GITHUB_STEP_SUMMARY
          fi

  configure-monitoring:
    needs: deploy-infrastructure
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Configure DataDog
        run: |
          # Install DataDog agent on both clusters
          echo "Configuring DataDog monitoring..."
          # Implementation would go here
      
      - name: Configure Splunk Forwarder
        run: |
          # Configure Splunk log forwarding
          echo "Configuring Splunk integration..."
          # Implementation would go here
      
     